from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.Login.as_view()),
    path('manage_user/', views.ManageUsersView.as_view()),
    path('freeze_user/', views.FreezeUserView.as_view()),
    path('manage_team/', views.ManageTeamView.as_view()),
    path('change_team/', views.ChangeTeamView.as_view()),
    path('my_profile/', views.MyProfileView.as_view()),
    path('others_profile/<int:id>/', views.OthersProfileView.as_view()),
    path('consult_my_planning/', views.MyPlanningView.as_view()),
    path('consult_my_schedule/', views.MyDailyScheduleView.as_view()),
    path('consult_my_pointing/', views.MyPointingView.as_view()),
    path('consult_others_planning/<int:id>/', views.ConsultOthersPlanningView.as_view()),
    path('consult_others_schedule/<int:id>/', views.ConsultOthersDailyScheduleView.as_view()),
    path('consult_filtered_schedule/', views.ConsultDailyScheduleView.as_view()),
    path('demand_message/', views.DemandMessageView.as_view()),
    path('manage_demand_message/', views.ManageDemandMessageView.as_view()), 
    path('manage_pointing_settings/', views.ManagePointingSettings.as_view()),
    path('get_pointing_settings/', views.GetPointingSettings.as_view()),
    path('check_system_sanity/', views.CheckSystemSanity.as_view()),
    path('justification/', views.JustificationView.as_view()),
    path('manage_justification/', views.ManageJustificationView.as_view()),
    path('justification_picture/<int:id>/', views.FetchJustificationPictureView.as_view()),
    path('change_profile_picture/', views.ChangeProfilePictureView.as_view()),
    path('profile_picture/<int:id>/', views.FetchProfilePictureView.as_view()),
    path('notifications/', views.NotificationsView.as_view()),
    path('notifications_count/', views.NotificationsCountView.as_view()),
    path('statistics/', views.StatisticsView.as_view()),
    path('manage_planning/', views.ManagePlanningView.as_view()),
    path('confirm_pointing/', views.ConfirmPointingView.as_view()),
    path('point_manually/', views.ManuallyPointingView.as_view()),
    path('point_qr/', views.QRPointingView.as_view()),
    path('get_point_qr/', views.GetQRPointingView.as_view()),
    path('point_face/', views.FaceRecognitionPointingView.as_view()),
]